### PR TITLE
Remove file url fields

### LINKED ISSUE #201: JSON:  FileUrl
Remove unnecessary fields of the FileUrl object in the JSON-testplans.
- `location`
- `storage`
Rename `content` to `url`.

### PR DESCRIPTION
**Pull request by bsels**
close #201

### CODE REVIEW

**Comment by niknetniko** [comment]
Does this break existing testplans? I don't know how many exercises there are, but if we can't update all at the same time, we might need to deprecate `content` and keep it for now, until all exercises are updated

**Comment by bsels** [comment]
Indeed this will break existing testplans, but the  only location is the `TESTed_challenges` repo.

**Review by niknetniko — APPROVED** [review]
As long as we don't wait too long to update that repo, it's OK for me.

**Comment by pdawyndt** [comment]
Can we update the exercises first? Seems like a simple search and replace in both the testplans and their generators?

**Comment by pdawyndt** [comment]
Should we also have a sample testplan for TESTed as an example of an exercise that works with files?

**Comment by bsels** [comment]
> Can we update the exercises first? Seems like a simple search and replace in both the testplans and their generators?

The JSON-testplans are updated, the generators aren't needed because it generates the YAML.

**Review by niknetniko — APPROVED** [review]

**Pull request merged**
