### PR TITLE
Add namespace for functions

### LINKED ISSUE #279: Support namespaces for function calls
Currently only objects, function calls and variables are supported.

But namespaces (like `java.lang.Math`) for function calls aren't yet supported.

In a previous version for function calls, namespaces (like `java.lang.Math`) where supported, but by the extensions for chained function calls this support is lost.

I suggest adding a class:
```python3
@dataclass
class Namespace:
    name: str # Name of the namespace
    package_path: List[str] = field(default_factory=list) # Package location
    type: Literal['namespace'] = 'namespace'
```

### PR DESCRIPTION
**Pull request by bsels**
Add JSON support for namespaces for functions.

close #279 

Question: should we support namespaces in the DSL-testplans?

### CODE REVIEW

**Comment by niknetniko** [comment]
At the moment, I'm hesitant to add explicit package support to TESTed, since that's a complex issue, and I'm not sure it's worth adding.

The old method with a manual string as namespace should still work, for example this (non-compiling) example:

```json
"input": {
   "type": "function",
   "name": "sin",
   "namespace": "java.lang.Math",
   "arguments": [{
     "type": "text",
     "data": "input-1"
   }]
},
```

Since the namespace is an `expression`, it can also be an `identifier`, which is a string, and I think those are just used in the generated code verbatim.

The main reason I'm hesitant to add the package support in its current form is that I don't think it adds anything you can't do with the normal expression (but I will have a more in-depth look at the code next week), except being less verbose, since it uses imports. Other thoughts (but again, I haven't looked at this in depth) right now:

- How imports work differs a lot from language to language, e.g. imports in Java or includes in C/C++.
- More advanced stuff will probably never be supported, e.g. static imports in Java, or the various import methods in Python, or Haskell stuff
- Some language have multiple ways, e.g. in Javascript we now use the node way, but we could also use the newer ES6 module syntaxis

**Comment by pdawyndt** [comment]
Does it require more than extending the grammar of the mini-language to support namespaced functions? Seems useful to also support in DSL if we only need to extend the grammar.

**Comment by bsels** [comment]
> Does it require more than extending the grammar of the mini-language to support namespaced functions? Seems useful to also support in DSL if we only need to extend the grammar.

We must use something like `namespace([<package>.]*<name>)` to distinquish between variables and properties and the namespace.

**Comment by bsels** [comment]
> At the moment, I'm hesitant to add explicit package support to TESTed, since that's a complex issue, and I'm not sure it's worth adding.

I know it's a complex issue, but the suggested approach depends on the namingconventions for the identifiers.
Therefore it's the suggested approach won't always work.
Example:
```json
"input": {
   "type": "function",
   "name": "sin",
   "namespace": "Math",
   "arguments": [{
     "type": "text",
     "data": "input-1"
   }]
},
```
In this example will `Math` be conventionalised to `math`.

I can remove the `package_path` field, if you think it's better, but the namespace object is needed for the namingconventions.

**Comment by niknetniko** [comment]
> I know it's a complex issue, but the suggested approach depends on the namingconventions for the identifiers.

While this is true, I don't think adding another field is the correct solution here, and better package support is out-of-scope for now.

**Pull request closed without merging**
