### PR TITLE
Update docker image to python:3.9.1-slim-buster

### PR DESCRIPTION
**Pull request by bsels**

### CODE REVIEW

**Review by niknetniko — CHANGES_REQUESTED** [review]
We also need to update the github actions to 3.9, or they'll be outdated immediately.

**Comment by niknetniko** [comment]
Haskell is broken again 😞

**Comment by bsels** [comment]
Running test local they succeeded all

**Comment by niknetniko** [comment]
Perhaps it's better to disable the Haskell tests for now, until we figure out a way to make the set-up more reliable? At least we're sure we don't break other stuff then.

**Review by niknetniko — APPROVED** [review]

**Pull request merged**
