### PR TITLE
Update description generator variables and functions

### PR DESCRIPTION
**Pull request by bsels**
Apply some suggestions of @pdawyndt for the template descriptions.

1. Add _plural_ forms for the natural type names.
2. Remove the constant `namespace_html`.
3. `namespace` will be adopted to the Markdown/HTML Context
4. Remove the constant `language_html`.
5. `language` is renamed to `programming_language` and will be adopted to the Markdown/HTML Context.
6. `programming_language_for_condition` contains always the unescaped programming language string.
7. The function `natural_type_name` is extended with a second parameter `plural` with default value `false`.
8. Add the constant `natural_language` contains the natural name of the natural language, with the `iso639-1` code as fallback.
9. Add the constant `natural_language_iso639` contains the `iso639-1` language code for the natural language.

### CODE REVIEW

**Comment by pdawyndt** [comment]
Maybe `programming_language_raw` instead of `programming_language_for_condition`?

**Review by niknetniko — APPROVED** [review]

**Comment by pdawyndt** [comment]
Voor de namen van de functies zou ik ook willen voorstellen (ter discussie):

- `function_name` vervangen door `function`
- `type_name` vervangen door `datatype`
- `natural_type_name` vervangen door `datatype_common`

**Comment by bsels** [comment]
> Voor de namen van de functies zou ik ook willen voorstellen (ter discussie):
> 
> * `function_name` vervangen door `function`
> * `type_name` vervangen door `datatype`
> * `natural_type_name` vervangen door `datatype_common`

Then I would also rename `global_var_name` by `global_variable`.

**Comment by pdawyndt** [comment]
What about simply `variable`?

**Comment by bsels** [comment]
> What about simply `variable`?

Will that not cause confusion with the local variables in the testplan?

**Comment by pdawyndt** [comment]
In MAKO templates some constants and functions seem to be replaced with formatting characters. For example, in Markdown, some replacement strings are enclosed in backticks. This way, the formatting characters are implicit in the MAKO templates and flexibility is lost. I would suggest to not include the formatting characters in the replacement string and put them explicitly in the template, as they would be in the description itself.

**Review by pdawyndt — APPROVED** [review]
I'm done with this iteration of reviewing the Dutch version of the TESTed documentation. I haven't reviewed the JSON testplan documentation for now, as it needs updating based on the changes made to TESTed while doing this round of review. 

I would suggest to publish this version of the documentation and finalize the Dutch version first before cleaning up the English version based on the blessed version of the Dutch documentation.

**Review by niknetniko — APPROVED** [review]

**Pull request merged**
